# Generated by Django 3.0.6 on 2020-09-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='icon',
        ),
    ]
