# Generated by Django 3.0.6 on 2020-09-15 07:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='linkdin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='opening_times',
            field=models.ManyToManyField(to='about.OpeningHours'),
        ),
    ]
