# Generated by Django 3.0.6 on 2020-09-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_url'),
        ('about', '0002_auto_20200915_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='youtube',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='license_number',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='opening_times',
            field=models.ManyToManyField(blank=True, to='about.OpeningHours'),
        ),
        migrations.CreateModel(
            name='socialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Twitter'), (4, 'Youtube'), (5, 'Linkdin')], unique=True)),
                ('account_url', models.URLField()),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, to='about.socialMediaAccount'),
        ),
    ]
