# Generated by Django 3.0.6 on 2020-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200921_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, to='about.SocialMediaAccount'),
        ),
    ]
