# Generated by Django 3.0.6 on 2020-05-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='images.Image')),
            ],
        ),
    ]
