# Generated by Django 3.0.6 on 2020-10-08 00:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=63, populate_from=['name'])),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
            ],
        ),
    ]
