# Generated by Django 3.0.6 on 2020-05-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_url'),
        ('services', '0006_auto_20200521_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
        migrations.DeleteModel(
            name='ServicesImage',
        ),
    ]
