# Generated by Django 3.0.6 on 2020-09-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200724_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='builder',
        ),
    ]
