# Generated by Django 3.0.6 on 2020-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('images', models.ManyToManyField(to='images.Image')),
            ],
        ),
    ]
