# Generated by Django 3.0.6 on 2020-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('date', models.DateField()),
                ('image_file', models.ImageField(upload_to='')),
                ('web_alt', models.CharField(max_length=64)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=127)),
            ],
        ),
    ]
