# Generated by Django 3.0.6 on 2020-10-07 04:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('name', models.CharField(default='about', editable=False, max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('name', models.CharField(default='contact', editable=False, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('name', models.CharField(default='home', editable=False, max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='')),
                ('call_to_action_text', models.CharField(max_length=27)),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about', models.BooleanField(default=False)),
                ('portfolio', models.BooleanField(default=False)),
                ('services', models.BooleanField(default=False)),
                ('home', models.BooleanField(default=False)),
                ('contact', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('name', models.CharField(default='portfolio', editable=False, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('name', models.CharField(choices=[('services', 'Services'), ('skills', 'Skills')], default='service', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(default='Cerulean')),
                ('cdn_url_path', models.URLField(default='https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/cerulean/bootstrap.min.css')),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pageManager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.PageManager')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.Template')),
            ],
        ),
    ]
