# Generated by Django 3.0.6 on 2020-07-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemanager',
            name='about',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemanager',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemanager',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemanager',
            name='portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemanager',
            name='services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='cdn_url_path',
            field=models.URLField(default='https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/cerulean/bootstrap.min.css'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(default='Cerulean'),
        ),
    ]
