# Generated by Django 3.0.6 on 2020-10-07 04:37

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('date', models.DateField()),
                ('image_file', models.ImageField(upload_to='images')),
                ('web_alt', models.CharField(max_length=64)),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=127, populate_from=['name'])),
            ],
        ),
    ]
