# Generated by Django 3.0.6 on 2020-10-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='web_alt',
        ),
    ]
