# Generated by Django 3.0.6 on 2020-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='test'),
        ),
    ]
