# Generated by Django 3.0.6 on 2020-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20200928_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
